[package]
name = "open-lark"
version = "0.2.3"
edition = "2021"
authors = ["ZoOL <zhooul@gmail.com>"]
readme = "README.md"
description = "Lark/Feishu Open API SDK(WIP)"
keywords = ["sdk", "feishu", "lark", "rest"]
categories = ["api-bindings"]
documentation = "https://docs.rs/open-lark"
repository = "https://github.com/foxzool/open-lark"
license = "MIT OR Apache-2.0"

[features]
websocket = ["tokio-tungstenite"]

[workspace]
members = ["crates/*"]

[dependencies]
lark-websocket-protobuf = { path = "crates/protobuf", version = "0.1.0" }
async-recursion = "1.1.1"
base64 = "0.22.1"
chrono = "0.4.38"
futures-util = { version = "0.3.30", default-features = false, features = [
    "sink",
    "std",
] }
hmac = "0.12.1"
lazy_static = "1.4.0"
log = "0.4.21"
kanal = "0.1.0-pre8"
quick_cache = { version = "0.5.1", features = [] }
rand = "0.9.0-alpha.1"
reqwest = { version = "0.12.4", features = ["json", "multipart"] }
simd-adler32 = "0.3.7"
serde_repr = "0.1.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
strum = "0.26.2"
strum_macros = "0.26.4"
thiserror = "1.0.61"
tokio = { version = "1.38", features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = "0.1.15"
url = { version = "2.5.0", features = ["serde"] }
tokio-tungstenite = { version = "0.23", features = ["rustls-tls-native-roots"], optional = true }
futures-channel = "0.3.30"
prost = "0.12.6"


[dev-dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.3"
uuid = { version = "1.8.0", features = ["v4"] }

[[example]]
name = "ws_client"
path = "examples/ws_client.rs"
required-features = ["websocket"]


[[example]]
name = "card_column_set"
path = "examples/card/column_set.rs"

[[example]]
name = "card_form_set"
path = "examples/card/form.rs"

[[example]]
name = "card_interactive"
path = "examples/card/interactive.rs"

[[example]]
name = "card_collapsible"
path = "examples/card/collapsible.rs"

[[example]]
name = "create_message"
path = "examples/api/im/v1/create_message.rs"

[[example]]
name = "list_message"
path = "examples/api/im/v1/list_message.rs"

[[example]]
name = "list_chat"
path = "examples/api/im/v1/list_chat.rs"

[[example]]
name = "file_upload_all"
path = "examples/api/drive/v1/files/upload_all.rs"

[[example]]
name = "file_download"
path = "examples/api/drive/v1/files/download.rs"


[[example]]
name = "root_meta"
path = "examples/api/drive/v2/explorer/meta.rs"

[[example]]
name = "create_folder"
path = "examples/api/drive/v2/explorer/create_folder.rs"

[[example]]
name = "list_folder"
path = "examples/api/drive/v2/explorer/list_folder.rs"

[[example]]
name = "get_permission"
path = "examples/api/drive/v2/permission/get.rs"

[[example]]
name = "patch_permission"
path = "examples/api/drive/v2/permission/patch.rs"

[[example]]
name = "search_user"
path = "examples/api/search/v1/user.rs"

# 电子表格

[[example]]
name = "sheet-add-rows-or-columns"
path = "examples/api/sheets/v2/spreadsheet/add_row_or_columns.rs"

[[example]]
name = "sheet-insert-rows-or-columns"
path = "examples/api/sheets/v2/spreadsheet/insert_row_or_columns.rs"

[[example]]
name = "sheet-update-rows-or-columns"
path = "examples/api/sheets/v2/spreadsheet/update_row_or_columns.rs"

[[example]]
name = "operate_spreadsheet_sheet"
path = "examples/api/sheets/v2/spreadsheet-sheet/operate.rs"

[[example]]
name = "update_spreadsheet_sheet_properties"
path = "examples/api/sheets/v2/spreadsheet-sheet/update.rs"

[[example]]
name = "create_spreadsheet"
path = "examples/api/sheets/v3/spreadsheet/create.rs"

[[example]]
name = "patch_spreadsheet"
path = "examples/api/sheets/v3/spreadsheet/patch.rs"

[[example]]
name = "get_spreadsheet"
path = "examples/api/sheets/v3/spreadsheet/get.rs"

[[example]]
name = "get_spreadsheet_sheet"
path = "examples/api/sheets/v3/spreadsheet-sheet/get.rs"

[[example]]
name = "query_spreadsheet_sheet"
path = "examples/api/sheets/v3/spreadsheet-sheet/query.rs"

[[example]]
name = "sheet_move_dimension"
path = "examples/api/sheets/v3/spreadsheet-sheet/move_dimension.rs"



[[example]]
name = "get_bitable"
path = "examples/api/bitable/v1/app/get.rs"

[[example]]
name = "app_table_record_search"
path = "examples/api/bitable/v1/app_table_record/search.rs"

[[example]]
name = "app_table_field_list"
path = "examples/api/bitable/v1/app_table_field/list.rs"
