[package]
name = "lark-websocket-protobuf"
version = "0.1.1"
edition = "2021"
authors = ["ZoOL <zhooul@gmail.com>"]
description = "Lark/Feishu websocket client protobuf definitions."
keywords = ["sdk", "feishu", "lark", "websocket"]
categories = ["api-bindings"]
documentation = "https://docs.rs/open-lark"
repository = "https://github.com/foxzool/open-lark"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = "1.6.0"
prost = "0.13.1"


[build-dependencies]
prost-build = "0.12.6"